# -*- coding: utf-8 -*-
"""Exercicio_compras_car_XGboost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyJwIUnkFzehcoXh9IFfazo_GdzKJN1u

# Base de propensão a compra de carros aplicando XGboost
"""

import xgboost as xgb
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

"""# Carregar a base de dados e verifique os tipos de dados, dados faltantes e dropar a coluna ID.

"""

base_car = pd.read_csv("/content/sample_data/CARRO_CLIENTES.csv")

print("Dimensão inicial da base:")
display(base_car.shape)

display(base_car.head())

#  Inspecionar  dados
print(">> Primeiras 5 linhas:")
print(base_car.head(), "\n")

print(">> Info geral do DataFrame:")
base_car.info()
print()

# estatisticas descritivas
print(">> Estatísticas descritivas (numéricas):")
print(base_car.describe(), "\n")

print(">> Estatísticas descritivas (tudo):")
print(base_car.describe(include='all'), "\n")

#  Checagem de valores ausentes
na_counts = base_car.isnull().sum()
na_pct = (na_counts / len(base_car) * 100).round(2)
ausente_car = pd.DataFrame({
    'contagem_ausentes': na_counts,
    'porcentagem_ausentes': na_pct
})
print(">> Valores ausentes por coluna:")
print(ausente_car, "\n")

# verificação de valores únicos para confirmar que não tem nenhum residuo

print(">> Valores únicos na coluna 'Gender':")
print(base_car['Gender'].unique())
print("\n")

base_car = base_car.drop('User ID', axis=1)

print("Dimensão da base após remover a coluna 'User ID':")
display(base_car.shape)

display(base_car.head())

"""# Aplicar o Label Encoder para a coluna Gender e excluir a coluna categórica.

"""

# Identificar todas as colunas categóricas (tipo 'object')
categorical_columns = base_car.select_dtypes(include='object').columns.tolist()

print("Colunas categóricas no DataFrame:")
for col in categorical_columns:
    print(f"- {col}")

le = LabelEncoder()
base_car['Gender'] = le.fit_transform(base_car['Gender'])

print("Valores únicos na coluna 'Gender' após Label Encoding:")
print(base_car['Gender'].unique())

display(base_car.head())

"""# Fazer a matriz de correlação e analise as váriaveis que parecem ter maior correlação com a váriavel target."""

# Heatmap de correlacao
num_cols = ['Gender', 'Age', 'AnnualSalary', 'Purchased']
corr = base_car[num_cols].corr()
plt.figure(figsize=(12,8))
im = plt.imshow(corr, vmin=-1, vmax=1)
plt.xticks(range(len(num_cols)), num_cols, rotation=45, ha='right')
plt.yticks(range(len(num_cols)), num_cols)
plt.colorbar(im, fraction=0.046, pad=0.04)
plt.title('Heatmap de Correlação')
plt.tight_layout()
plt.show()

print("Correlação com a variável target 'Purchased':")
print(corr['Purchased'].sort_values(ascending=False))

print("\nAnálise:")
print("A variável 'Age' possui a maior correlação positiva com 'Purchased' (0.616).")
print("Em seguida, 'AnnualSalary' também mostra uma correlação positiva significativa (0.365).")
print("A variável 'Gender' apresenta uma correlação muito baixa e negativa (-0.047), indicando pouca influência direta no 'Purchased' no que tange a correlação linear.")

"""# Fazer a separação da base em X e Y e em seguida nas bases de treino e teste."""

X = base_car.drop('Purchased', axis=1)
Y = base_car['Purchased']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

print("Dimensão de X_train:", X_train.shape)
print("Dimensão de X_test:", X_test.shape)
print("Dimensão de y_train:", y_train.shape)
print("Dimensão de y_test:", y_test.shape)

"""# Treinar o modelo Xgboost com sua base de treino.
Pesquise alguns hyperparametros na bibllioteca para utilizar, utilize ao menos 2.
"""

model = xgb.XGBClassifier(
    objective='binary:logistic',
    n_estimators=100,
    learning_rate=0.1,
    use_label_encoder=False,
    eval_metric='logloss',
    random_state=42
)

model.fit(X_train, y_train)

print("Modelo XGBoost treinado com sucesso!")

"""# Realizar as previsões para a base de teste, trazendo as probabilidades das previsões."""

Y_pred = model.predict(X_test)           # Previsões das classes
Y_pred_prob = model.predict_proba(X_test)  # Probabilidades de cada classe

Y_pred_prob

"""# Fazer a transformação das probabilidades nas previsões binárias e avaliar o desempenho do modelo."""

# Então uma vez que temos as probabilidades, fazemos a transformação das previsões e os rótulos de volta para os rótulos originais
Y_pred_original = le.inverse_transform(Y_pred)
Y_test_original = le.inverse_transform(y_test)

accuracy = accuracy_score(Y_test_original, Y_pred_original)
report = classification_report(Y_test_original, Y_pred_original)
conf_matrix = confusion_matrix(Y_test_original, Y_pred_original)

print(f'Acurácia: {accuracy}')
print('Relatório de Classificação:')
print(report)
print('Matriz de Confusão:')
print(conf_matrix)

"""# Trazer a lista com a feature importance."""

importances = model.get_booster().get_score(importance_type='gain')

# Convertendo o dicionário de importâncias para um DataFrame
importance_df = pd.DataFrame(list(importances.items()), columns=['Feature', 'Importance'])
importance_df['Importance'] = importance_df['Importance'].astype(float)
importance_df = importance_df.sort_values(by='Importance', ascending=False)

print(importance_df)

print('Correlação com a variável target \'Purchased\':')
print(corr['Purchased'].sort_values(ascending=False))

print('\nImportância das Features (XGBoost):')
print(importance_df)

"""Sim, são as mesmas( Age e AnnualSalary) que apresentaram maior correlação positiva com a variável target 'Purchased' na matriz de correlação com Age sendo a mais influente em ambos os casos. Por outro lado, Gender apresentou baixa correlação e a menor importância no modelo XGBoost."""